--- 
:accounts: 
  :default: 
    :name: Ryan Stephenson
    :email: rycs42@gmail.com
    :alternates: 
    - rycs42@tamu.edu
    - rstephenson@athletics.tamu.edu
    :sendmail: msmtp --account=gmail -t
    :signature: /home/ryan/.signature
:editor: nano
:thread_by_subject: false
:edit_signature: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:confirm_no_attachments: true
:confirm_top_posting: true
:discard_snippets_from_encrypted_messages: false
:default_attachment_save_dir: ""
:sent_source: sup://sent
:poll_interval: 100
